baseURL = "https://jacobearle.xyz"
languageCode = "en-us"
title = "Jacob Earle"
theme = "ananke"
googleAnalytics = 'G-JDYPEPWZQ1'

SectionPagesMenu = "main"

[params]
  author = "Jacob Earle"
  favicon = ""
  site_logo = ""
  description = "Jacob Earle's personal website!"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/jacob-earle"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jacob-earle-434a36192"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/blueandblackbanner.jpg"
  body_classes = "avenir bg-washed-blue"